<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<div class="module-heading"><div><p class="eyebrow dark">${moduleKicker}</p><h2>${moduleTitle}</h2><p>${moduleDescription}</p></div><c:if test="${not empty primaryAction}"><button class="button button-gold" data-demo-toast="${primaryAction} — chức năng mẫu đã sẵn sàng">＋ ${primaryAction}</button></c:if></div>
<div class="module-toolbar"><form><input placeholder="Tìm kiếm theo tên, mã hoặc từ khóa"><button>Tìm kiếm</button></form><select><option>Tất cả trạng thái</option><option>Đang hoạt động</option><option>Chờ xử lý</option><option>Đã hoàn thành</option></select><button>⚙ Bộ lọc</button></div>
<c:choose>
    <c:when test="${tableKind == 'orders'}"><div class="dashboard-card"><div class="table-wrap"><table><thead><tr><th>Mã đơn</th><th>Khách hàng</th><th>Thời gian</th><th>Tổng tiền</th><th>Trạng thái</th><th></th></tr></thead><tbody><c:forEach items="${orders}" var="order"><tr><td><b>#${order.code}</b></td><td>${order.customerName}</td><td>${order.createdAt}</td><td><fmt:formatNumber value="${order.total}" pattern="#,##0" />₫</td><td><span class="status-badge ${order.status.cssClass}">${order.status.label}</span></td><td><a class="table-action" href="${cp}/manage/sales/order-detail?code=${order.code}">Chi tiết →</a></td></tr></c:forEach></tbody></table></div></div></c:when>
    <c:when test="${tableKind == 'products'}"><div class="dashboard-card"><div class="table-wrap"><table><thead><tr><th>Sản phẩm</th><th>SKU</th><th>Giá bán</th><th>Tồn kho</th><th>Trạng thái</th><th></th></tr></thead><tbody><c:forEach items="${products}" var="product"><tr><td><div class="table-product"><img src="${cp}/assets/images/${product.image}" alt=""><span><b>${product.name}</b><small>${product.brand}</small></span></div></td><td>${product.sku}</td><td><fmt:formatNumber value="${product.price}" pattern="#,##0" />₫</td><td><b>${product.stock}</b></td><td><span class="status-badge ${product.stock < 6 ? 'warning' : 'success'}">${product.stock < 6 ? 'Sắp hết' : 'Đang bán'}</span></td><td><button class="table-action" data-demo-toast="Đã mở chi tiết sản phẩm">Chỉnh sửa</button></td></tr></c:forEach></tbody></table></div></div></c:when>
    <c:when test="${tableKind == 'permissions'}"><div class="dashboard-card permission-matrix"><table><thead><tr><th>Module</th><th>Xem</th><th>Thêm</th><th>Sửa</th><th>Duyệt</th><th>Xuất báo cáo</th></tr></thead><tbody><c:forTokens items="Sản phẩm,Đơn hàng,Khách hàng,Kho hàng,Voucher,Báo cáo" delims="," var="item"><tr><td><b>${item}</b></td><td><input type="checkbox" checked></td><td><input type="checkbox" checked></td><td><input type="checkbox" checked></td><td><input type="checkbox"></td><td><input type="checkbox"></td></tr></c:forTokens></tbody></table><button class="button button-dark" data-demo-toast="Đã lưu ma trận phân quyền">Lưu phân quyền</button></div></c:when>
    <c:when test="${formMode}"><div class="dashboard-card module-form"><div class="form-grid two"><label>Mã phiếu / Mã tham chiếu<input value="TỰ ĐỘNG" readonly></label><label>Ngày tạo<input type="date" value="2026-08-02"></label><label>Đối tác / Nhà cung cấp<select><option>Nhà cung cấp WatchStore</option><option>Đối tác Seiko Việt Nam</option></select></label><label>Người phụ trách<input value="${sessionScope.user.fullName}"></label><label class="full-field">Ghi chú<textarea placeholder="Nhập nội dung ghi chú"></textarea></label></div><div class="line-items"><div><b>Danh sách sản phẩm</b><button data-demo-toast="Đã thêm dòng sản phẩm">＋ Thêm sản phẩm</button></div><table><thead><tr><th>Sản phẩm</th><th>Biến thể</th><th>Số lượng</th><th>Đơn giá</th><th>Thành tiền</th></tr></thead><tbody><tr><td>Edifice Sapphire</td><td>Xanh / Dây thép</td><td><input type="number" value="10"></td><td>2.800.000₫</td><td><b>28.000.000₫</b></td></tr></tbody></table></div><div class="form-actions"><button class="button">Lưu nháp</button><button class="button button-gold" data-demo-toast="Đã xác nhận chứng từ mẫu">Xác nhận</button></div></div></c:when>
    <c:otherwise><div class="module-cards"><c:forEach begin="1" end="6" var="i"><article><div class="module-card-icon">${moduleIcon}</div><span class="status-badge success">Đang hoạt động</span><h3>${moduleItemName} ${i}</h3><p>Dữ liệu mẫu phục vụ phát triển giao diện và luồng nghiệp vụ. Có thể thay thế bằng dữ liệu SQL Server.</p><div><button data-demo-toast="Đã mở chi tiết">Chi tiết</button><button data-demo-toast="Đã mở chỉnh sửa">Chỉnh sửa</button></div></article></c:forEach></div></c:otherwise>
</c:choose>
